from dataclasses import dataclass
from pathlib import Path

from src.core.config import DATA_DIR, ensure_data_dir

RULE_LABELS: dict[str, str] = {
    "terceiro_queda50": "Regra 1 – 3º com queda ≥ 50% vs 2º",
    "lider_volume_total": "Regra 2 – Líder com volume dominante",
    "forecast_odds": "Forecast Odds (Timeform)",
}
RULE_LABELS_INV: dict[str, str] = {v: k for k, v in RULE_LABELS.items()}

ensure_data_dir()
HORSES_DATA_DIR = DATA_DIR / "horses"
HORSES_DATA_DIR.mkdir(parents=True, exist_ok=True)

RAW_RESULT_DIR = HORSES_DATA_DIR / "Result"
RAW_TIMEFORM_TOP3_DIR = HORSES_DATA_DIR / "timeform_top3"
RAW_TIMEFORM_FORECAST_DIR = HORSES_DATA_DIR / "TimeformForecast"
RAW_SIGNALS_TIMEFORM_DIR = HORSES_DATA_DIR / "signals" / "timeform"
RAW_SIGNALS_SPORTINGLIFE_DIR = HORSES_DATA_DIR / "signals" / "sportinglife"
RAW_SPORTINGLIFE_TOP3_DIR = HORSES_DATA_DIR / "sportinglife_top3"
RAW_SPORTINGLIFE_FORECAST_DIR = HORSES_DATA_DIR / "SportingLifeForecast"

PROCESSED_DIR = HORSES_DATA_DIR / "processed"
PROCESSED_RESULT_DIR = PROCESSED_DIR / "Result"
PROCESSED_TIMEFORM_TOP3_DIR = PROCESSED_DIR / "timeform_top3"
PROCESSED_TIMEFORM_FORECAST_DIR = PROCESSED_DIR / "TimeformForecast"
PROCESSED_SIGNALS_TIMEFORM_DIR = PROCESSED_DIR / "signals" / "timeform"
PROCESSED_SIGNALS_SPORTINGLIFE_DIR = PROCESSED_DIR / "signals" / "sportinglife"
PROCESSED_SPORTINGLIFE_TOP3_DIR = PROCESSED_DIR / "sportinglife_top3"
PROCESSED_SPORTINGLIFE_FORECAST_DIR = PROCESSED_DIR / "SportingLifeForecast"


@dataclass(frozen=True)
class Settings:
    DATA_DIR: Path = HORSES_DATA_DIR
    RAW_RESULT_DIR: Path = RAW_RESULT_DIR
    RAW_TIMEFORM_TOP3_DIR: Path = RAW_TIMEFORM_TOP3_DIR
    RAW_TIMEFORM_FORECAST_DIR: Path = RAW_TIMEFORM_FORECAST_DIR
    RAW_SIGNALS_TIMEFORM_DIR: Path = RAW_SIGNALS_TIMEFORM_DIR
    RAW_SIGNALS_SPORTINGLIFE_DIR: Path = RAW_SIGNALS_SPORTINGLIFE_DIR
    RAW_SPORTINGLIFE_TOP3_DIR: Path = RAW_SPORTINGLIFE_TOP3_DIR
    RAW_SPORTINGLIFE_FORECAST_DIR: Path = RAW_SPORTINGLIFE_FORECAST_DIR
    PROCESSED_DIR: Path = PROCESSED_DIR
    PROCESSED_RESULT_DIR: Path = PROCESSED_RESULT_DIR
    PROCESSED_TIMEFORM_TOP3_DIR: Path = PROCESSED_TIMEFORM_TOP3_DIR
    PROCESSED_TIMEFORM_FORECAST_DIR: Path = PROCESSED_TIMEFORM_FORECAST_DIR
    PROCESSED_SIGNALS_TIMEFORM_DIR: Path = PROCESSED_SIGNALS_TIMEFORM_DIR
    PROCESSED_SIGNALS_SPORTINGLIFE_DIR: Path = PROCESSED_SIGNALS_SPORTINGLIFE_DIR
    PROCESSED_SPORTINGLIFE_TOP3_DIR: Path = PROCESSED_SPORTINGLIFE_TOP3_DIR
    PROCESSED_SPORTINGLIFE_FORECAST_DIR: Path = PROCESSED_SPORTINGLIFE_FORECAST_DIR
    BETFAIR_BASE_URL: str = "https://www.betfair.com/exchange/plus/"
    BETFAIR_HORSE_RACING_URL: str = "https://www.betfair.com/exchange/plus/horse-racing"
    TIMEFORM_BASE_URL: str = "https://www.timeform.com/horse-racing"
    SPORTINGLIFE_BASE_URL: str = "https://www.sportinglife.com/racing/results"
    SELENIUM_HEADLESS: bool = False
    SELENIUM_PAGELOAD_TIMEOUT_SEC: int = 5
    SELENIUM_IMPLICIT_WAIT_SEC: int = 3
    SELENIUM_EXPLICIT_WAIT_SEC: int = 2
    TIMEFORM_MIN_DELAY_SEC: float = 0.5
    TIMEFORM_MAX_DELAY_SEC: float = 1.0
    SPORTINGLIFE_MIN_DELAY_SEC: float = 0.3
    SPORTINGLIFE_MAX_DELAY_SEC: float = 0.6
    CSV_ENCODING: str = "utf-8-sig"
    LOG_LEVEL: str = "INFO"
    FORECAST_ODDS_BACK_MIN_VALUE_RATIO: float = 1.00
    FORECAST_ODDS_LAY_MAX_VALUE_RATIO: float = 1.00


settings = Settings()

__all__ = [
    "RULE_LABELS",
    "RULE_LABELS_INV",
    "settings",
    "Settings",
    "HORSES_DATA_DIR",
    "RAW_RESULT_DIR",
    "RAW_TIMEFORM_TOP3_DIR",
    "RAW_TIMEFORM_FORECAST_DIR",
    "RAW_SIGNALS_TIMEFORM_DIR",
    "RAW_SIGNALS_SPORTINGLIFE_DIR",
    "RAW_SPORTINGLIFE_TOP3_DIR",
    "RAW_SPORTINGLIFE_FORECAST_DIR",
    "PROCESSED_DIR",
    "PROCESSED_RESULT_DIR",
    "PROCESSED_TIMEFORM_TOP3_DIR",
    "PROCESSED_TIMEFORM_FORECAST_DIR",
    "PROCESSED_SIGNALS_TIMEFORM_DIR",
    "PROCESSED_SIGNALS_SPORTINGLIFE_DIR",
    "PROCESSED_SPORTINGLIFE_TOP3_DIR",
    "PROCESSED_SPORTINGLIFE_FORECAST_DIR",
]
